INSERT INTO users (username, email, password, role) VALUES
('john_doe', 'john@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user'),
('jane_doe', 'jane@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user'),
('admin_1', 'admin1@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'admin'),
('admin_2', 'admin2@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'admin'),
('admin_3', 'admin3@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'admin'),
('user_1', 'user1@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user'),
('user_2', 'user2@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user'),
('user_3', 'user3@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user'),
('user_4', 'user4@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user'),
('user_5', 'user5@example.com', '$2b$10$81N.IzoZXKRH2x4sDt/.9.ZKnqyaQjTGVn6QHlekzW1rrcfDh9z4u', 'user');

INSERT INTO categories (name, description, user_id) VALUES
('Jedzenie', 'Wydatki na jedzenie i napoje', 1),
('Transport', 'Koszty podróży i transportu', 1),
('Rozrywka', 'Koszty związane z rozrywką', 2),
('Zdrowie', 'Wydatki na zdrowie', 3),
('Edukacja', 'Wydatki na naukę i kursy', 4),
('Technologia', 'Zakupy technologiczne', 5),
('Mieszkanie', 'Opłaty za mieszkanie', 6),
('Odzież', 'Zakupy odzieżowe', 7),
('Sport', 'Koszty sportu i rekreacji', 8),
('Hobby', 'Wydatki na hobby', 9),
('Rachunki', 'Wydatki na media i opłaty domowe', 1),
('Podróże', 'Koszty podróży i wyjazdów', 1),
('Zakupy', 'Codzienne zakupy spożywcze i inne', 1),
('Zdrowie', 'Wydatki na zdrowie i ubezpieczenia', 1),
('Rozrywka', 'Wydatki na rozrywkę i hobby', 1);

INSERT INTO expenses (title, price, note, date, category_id, user_id) VALUES
('Zakupy spożywcze', 100.50, 'Lidl', '2025-01-10', 1, 1),
('Bilet miesięczny', 120.00, 'ZTM', '2025-01-01', 2, 1),
('Netflix', 29.99, 'Abonament', '2025-01-08', 3, 2),
('Wizyta u dentysty', 200.00, 'Stomatolog', '2025-01-05', 4, 3),
('Kurs programowania', 1000.00, 'Online', '2025-01-06', 5, 4),
('Laptop', 3500.00, 'Zakup nowego laptopa', '2025-01-09', 6, 5),
('Czynsz', 1800.00, 'Opłaty miesięczne', '2025-01-02', 7, 6),
('Nowa kurtka', 400.00, 'Zara', '2025-01-07', 8, 7),
('Karnet na siłownię', 150.00, 'Siłownia', '2025-01-03', 9, 8),
('Zakupy do modelarstwa', 300.00, 'Materiały', '2025-01-04', 10, 9),
('Obiad w restauracji', 80.00, 'Lunch z rodziną', '2025-01-02', 1, 1),
('Zakupy warzywne', 50.00, 'Zakup warzyw na targu', '2025-01-03', 1, 1),
('Taxi', 45.00, 'Podróż do biura', '2025-01-04', 2, 1),
('Weekendowy wyjazd', 500.00, 'Wycieczka do Krakowa', '2025-01-05', 2, 1),
('Cinema City', 35.00, 'Bilet na film', '2025-01-06', 3, 2),
('Spotify', 19.99, 'Miesięczny abonament', '2025-01-07', 3, 2),
('Apteka', 100.00, 'Leki na przeziębienie', '2025-01-08', 4, 3),
('Wizyta u okulisty', 250.00, 'Badanie wzroku', '2025-01-09', 4, 3),
('Książka', 40.00, 'Podręcznik do nauki', '2025-01-10', 5, 4),
('Kurs online', 500.00, 'Szkolenie z marketingu', '2025-01-11', 5, 4),
('Smartfon', 2000.00, 'Nowy iPhone', '2025-01-12', 6, 5),
('Akcesoria komputerowe', 150.00, 'Mysz i klawiatura', '2025-01-13', 6, 5),
('Rachunek za wodę', 120.00, 'Miesięczna opłata', '2025-01-14', 7, 6),
('Opłata za internet', 70.00, 'Miesięczny abonament', '2025-01-15', 7, 6),
('Nowe buty', 300.00, 'Zakup adidasów', '2025-01-16', 8, 7),
('Letnia sukienka', 200.00, 'Promocja w sklepie', '2025-01-17', 8, 7),
('Trening personalny', 100.00, 'Siłownia', '2025-01-18', 9, 8),
('Zajęcia fitness', 120.00, 'Karnet miesięczny', '2025-01-19', 9, 8),
('Farby olejne', 150.00, 'Materiały do malowania', '2025-01-20', 10, 9),
('Klocki LEGO', 300.00, 'Hobby dzieciństwa', '2025-01-21', 10, 9),
('Rachunek za prąd', 200.50, 'Energia elektryczna za grudzień', '2025-01-10', 11, 1),
('Woda i ścieki', 120.00, 'Opłata za wodę i ścieki', '2025-01-05', 11, 1),
('Weekendowy wypad', 500.00, 'Wycieczka do Zakopanego', '2025-01-08', 12, 1),
('Zakupy w supermarkecie', 150.00, 'Lidl - cotygodniowe zakupy', '2025-01-03', 13, 1),
('Wizyta u dentysty', 250.00, 'Stomatolog - leczenie zęba', '2025-01-02', 14, 1),
('Netflix', 30.00, 'Abonament miesięczny', '2025-01-06', 15, 1),
('Spotify', 19.99, 'Muzyka na miesiąc', '2025-01-07', 15, 1),
('Nowa książka', 45.00, 'Nowość wydawnicza - kryminał', '2025-01-09', 15, 1),
('Zakupy online', 300.00, 'Nowe słuchawki z Amazona', '2025-01-04', 13, 1),
('Lekarstwa', 100.00, 'Leki na przeziębienie', '2025-01-10', 14, 1),
('Obiad w restauracji', 120.00, 'Kolacja z rodziną', '2025-01-11', 15, 1),
('Bilet na koncert', 250.00, 'Koncert ulubionego zespołu', '2025-01-15', 15, 1),
('Opłata za internet', 70.00, 'Miesięczny abonament', '2025-01-12', 11, 1),
('Zakupy odzieżowe', 400.00, 'Nowe buty i kurtka', '2025-01-13', 13, 1);

INSERT INTO articles (title, content, link, author, date) VALUES
('10 sposobów na oszczędzanie pieniędzy', 'Oszczędzanie jest kluczowe...', 'https://example.com/article3', 'Anna Nowak', '2025-01-01'),
('Jak zaplanować budżet?', 'Planowanie budżetu jest pierwszym krokiem...', 'https://example.com/article4', 'Piotr Kowalski', '2025-01-02'),
('Minimalizm finansowy', 'Minimalizm pomaga zredukować...', 'https://example.com/article5', 'Katarzyna Wiśniewska', '2025-01-03'),
('Kiedy oszczędzanie przynosi efekty?', 'Cierpliwość w oszczędzaniu...', 'https://example.com/article6', 'Jan Zieliński', '2025-01-04'),
('Najlepsze aplikacje do zarządzania budżetem', 'W artykule omawiamy...', 'https://example.com/article7', 'Maria Maj', '2025-01-05'),
('5 strategii na ograniczenie wydatków', 'W czasach inflacji...', 'https://example.com/article8', 'Tomasz Kaczmarek', '2025-01-06'),
('Kredyty i oszczędności', 'Kiedy warto brać kredyt...', 'https://example.com/article9', 'Magdalena Lewandowska', '2025-01-07'),
('Poradnik początkującego inwestora', 'Inwestowanie może być...', 'https://example.com/article10', 'Krzysztof Nowicki', '2025-01-08'),
('Oszczędzanie na podróże', 'Podróże nie muszą być drogie...', 'https://example.com/article11', 'Anna Kwiatkowska', '2025-01-09'),
('Zakupy online a oszczędzanie', 'Jak kupować mądrze online...', 'https://example.com/article12', 'Michał Szymański', '2025-01-10'),
('Minimalizm w codziennym życiu', 'Czy mniej znaczy więcej?...', 'https://example.com/article13', 'Zofia Wojciechowska', '2025-01-11'),
('Porady dotyczące oszczędzania energii', 'Oszczędzanie energii w domu...', 'https://example.com/article14', 'Adam Nowak', '2025-01-12'),
('Jak planować większe zakupy?', 'Planowanie dużych wydatków...', 'https://example.com/article15', 'Ewa Malinowska', '2025-01-13'),
('Zalety prowadzenia budżetu', 'Budżet domowy pozwala...', 'https://example.com/article16', 'Paweł Bąk', '2025-01-14'),
('Jak zbudować poduszkę finansową?', 
 'Budowanie poduszki finansowej to kluczowy krok w zarządzaniu finansami osobistymi. Poduszka finansowa to oszczędności, które mogą być wykorzystane w sytuacjach awaryjnych, takich jak utrata pracy, nagłe wydatki zdrowotne czy pilne naprawy. Aby zbudować taką poduszkę, warto zacząć od analizy swoich miesięcznych wydatków i ustalić, ile pieniędzy będziesz potrzebować, aby przeżyć przez 3-6 miesięcy. Ważne jest również, aby regularnie odkładać nawet niewielkie kwoty. Najlepiej trzymać te oszczędności na osobnym koncie oszczędnościowym, które zapewnia szybki dostęp do środków.', 
 'https://example.com/article23', 
 'Anna Nowak', 
 '2025-01-01'),
('Minimalizm w finansach osobistych: mniej znaczy więcej', 
 'Minimalizm w finansach polega na skupieniu się na tym, co naprawdę istotne, oraz redukowaniu zbędnych wydatków. Oznacza to, że zamiast kupować wiele tanich rzeczy, warto inwestować w produkty lepszej jakości, które będą służyć przez długi czas. Minimalizm pozwala również na oszczędzanie większych kwot, które można przeznaczyć na ważniejsze cele, takie jak podróże, edukacja czy emerytura. Minimalizm to nie tylko sposób zarządzania finansami, ale także styl życia, który pozwala cieszyć się tym, co naprawdę ważne.', 
 'https://example.com/article24', 
 'Piotr Kowalski', 
 '2025-01-02'),
('10 kroków do skutecznego planowania budżetu', 
 'Planowanie budżetu to fundament zdrowych finansów. Po pierwsze, zidentyfikuj swoje dochody i wydatki. Następnie podziel je na kategorie, takie jak jedzenie, mieszkanie, transport czy rozrywka. Kluczowe jest również monitorowanie tych wydatków co miesiąc, aby upewnić się, że pozostajesz w wyznaczonych limitach. Warto również wyznaczyć sobie cele finansowe, takie jak oszczędzanie na wakacje czy spłatę długów. Pamiętaj, aby planować budżet realistycznie i zostawić miejsce na nieprzewidziane wydatki.', 
 'https://example.com/article25', 
 'Katarzyna Wiśniewska', 
 '2025-01-03'),
('Jak skutecznie oszczędzać na emeryturę?', 
 'Oszczędzanie na emeryturę to wyzwanie, które wymaga konsekwencji i odpowiedniego planowania. Zacznij od określenia, ile pieniędzy będziesz potrzebować na spokojną emeryturę. Następnie wybierz odpowiednie narzędzia inwestycyjne, takie jak konta emerytalne, fundusze inwestycyjne lub nieruchomości. Kluczowe jest również, aby regularnie wpłacać środki i nie wypłacać ich przed czasem, aby mogły pracować dla Ciebie dzięki procentowi składanemu. Jeśli zaczynasz wcześnie, nawet niewielkie wpłaty mogą przynieść duże efekty w dłuższym okresie.', 
 'https://example.com/article26', 
 'Jan Zieliński', 
 '2025-01-04'),
('Jakie są najczęstsze błędy w oszczędzaniu?', 
 'Oszczędzanie pieniędzy może być trudne, szczególnie jeśli popełniasz pewne błędy. Jednym z najczęstszych jest brak celu oszczędnościowego. Bez konkretnego celu łatwo jest zrezygnować z regularnego odkładania pieniędzy. Inny błąd to trzymanie oszczędności na koncie, które nie generuje żadnych odsetek. Warto poszukać lepszych opcji, takich jak konta oszczędnościowe lub fundusze inwestycyjne. Kolejnym błędem jest nadmierne poleganie na kredytach i brak kontrolowania swoich długów, co prowadzi do problemów finansowych w przyszłości.', 
 'https://example.com/article27', 
 'Maria Maj', 
 '2025-01-05'),
('Inwestowanie dla początkujących: pierwsze kroki', 
 'Inwestowanie może wydawać się skomplikowane, ale dla początkujących kluczowe jest zrozumienie podstawowych zasad. Zacznij od zdefiniowania swoich celów inwestycyjnych, takich jak budowanie bogactwa czy ochrona kapitału. Następnie wybierz odpowiednie narzędzia, takie jak akcje, obligacje, fundusze ETF czy nieruchomości. Pamiętaj, aby zawsze dywersyfikować swoje inwestycje, aby zminimalizować ryzyko. Inwestowanie wymaga czasu i cierpliwości, ale może przynieść znaczące zyski w dłuższej perspektywie.', 
 'https://example.com/article28', 
 'Tomasz Kaczmarek', 
 '2025-01-06'),
('Czy warto oszczędzać na podróże?', 
 'Podróże są jednym z najbardziej inspirujących sposobów na spędzanie czasu, ale mogą być kosztowne. Aby zaoszczędzić na podróże, warto zacząć planować z dużym wyprzedzeniem. Szukaj tanich biletów lotniczych i korzystaj z promocji. Zamiast hoteli, rozważ wynajem mieszkań lub korzystanie z platform takich jak Couchsurfing. Warto również unikać restauracji turystycznych i wybierać lokalne miejsca, które często są tańsze i oferują autentyczne jedzenie. Oszczędzanie na podróże nie oznacza rezygnacji z komfortu, ale wybieranie mądrzejszych opcji.', 
 'https://example.com/article29', 
 'Magdalena Lewandowska', 
 '2025-01-07'),
('Jak oszczędzać na rachunkach domowych?', 
 'Oszczędzanie na rachunkach domowych to jeden z najprostszych sposobów na zmniejszenie miesięcznych wydatków. Zacznij od analizy swoich rachunków za prąd, wodę i gaz. Wprowadź energooszczędne rozwiązania, takie jak LED-y czy urządzenia o niższym zużyciu energii. Sprawdź, czy możesz zmienić dostawcę usług na tańszego. Zainwestuj w termostaty i systemy zarządzania energią, które pozwalają kontrolować zużycie w czasie rzeczywistym. Nawet małe zmiany, takie jak zakręcanie wody podczas mycia zębów, mogą przynieść znaczące oszczędności.', 
 'https://example.com/article30', 
 'Adam Nowak', 
 '2025-01-08'),
('Planowanie świątecznego budżetu', 
 'Święta to czas radości, ale także wydatków. Aby uniknąć problemów finansowych, warto wcześniej zaplanować budżet. Określ, ile możesz wydać na prezenty, jedzenie i dekoracje. Zastanów się, które wydatki są naprawdę konieczne, a które można ograniczyć. Korzystaj z promocji i kupuj prezenty z wyprzedzeniem. Możesz także rozważyć własnoręczne przygotowanie upominków, które są tańsze, a jednocześnie bardziej osobiste. Święta mogą być wyjątkowe, nawet jeśli zdecydujesz się na skromniejsze wydatki.', 
 'https://example.com/article31', 
 'Ewa Malinowska', 
 '2025-01-09'),
('Dlaczego warto prowadzić budżet domowy?', 
 'Budżet domowy to nie tylko sposób na kontrolowanie wydatków, ale także narzędzie, które pomaga osiągnąć cele finansowe. Dzięki budżetowi możesz zobaczyć, gdzie przepływają Twoje pieniądze i zidentyfikować obszary, w których można zaoszczędzić. Prowadzenie budżetu uczy dyscypliny finansowej i pozwala unikać zadłużenia. Warto regularnie analizować swój budżet i dostosowywać go do zmieniających się potrzeb. To prosty krok, który może znacząco poprawić Twoją sytuację finansową.', 
 'https://example.com/article32', 
 'Paweł Bąk', 
 '2025-01-10');